version: '2.0'
services:
  web:
    image: fredericobormann/dryck
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DATABASE: postgres
      GIN_MODE: release
      HTTP_PASSWORD: mysecretpassword
      JWT_SECRET: changethisinproduction
    ports:
      - "8089:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
